captainVersion: 4
caproverOneClickApp:
    instructions:
        start: Jitsu
        end: Jitsu is deployed. Visit http://$$cap_appname.$$cap_root_domain/configurator to continue.
########
services:
  $$cap_appname:
    container_name: $$cap_appname
    image: jitsucom/jitsu
    environment:
      REDIS_URL: redis://srv-captain--$$cap_appname-redis:6379
      USER_RECOGNITION_ENABLED: true
      USER_RECOGNITION_REDIS_URL: redis://srv-captain--$$cap_appname-redis-users-recognition:6379
    depends_on:
      - $$cap_appname-redis
    volumes:
      -  $$cap_appname-configurator-logs:/home/configurator/data/logs
      -  $$cap_appname-server-logs:/home/eventnative/data/logs
      -  $$cap_appname-server-logs-events:/home/eventnative/data/logs/events
      - /var/run/docker.sock:/var/run/docker.sock
      - $$cap_appname-workspace:/home/eventnative/data/airbyte
    restart: always
    ports:
      - "8000:8000"
    caproverExtra:
      containerHttpPort: '8000'
  $$cap_appname-redis:
    container_name: $$cap_appname-redis
    image: redis:6.2.4-alpine
    volumes:
      -  $$cap_appname-redis-data:/data
    restart: always
    caproverExtra:
      notExposeAsWebApp: 'true'
  $$cap_appname-redis-users-recognition:
    container_name: $$cap_appname-redis-users-recognition
    image: redis:6.2.4-alpine
    volumes:
      -  $$cap_appname-redis-users-recognition-data:/data
    restart: always
    caproverExtra:
      notExposeAsWebApp: 'true'
#volumes:
#  workspace:
#    name: $$cap_appname-workspace
