captainVersion: 4
caproverOneClickApp:
    variables:
        - id: $$cap_posthog_secret_key
          label: Random secret key
          defaultValue: $$cap_gen_random_hex(16)
    instructions:
        start: Posthog
        end: Posthog is deployed. Visit $$cap_appname.$$cap_root_domain to continue.
####################        
services:
    $$cap_appname-db:
        container_name: $$cap_appname-db
        environment:
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
            POSTGRES_USER: posthog
        image: postgres:13-alpine
        volumes:
            - $$cap_appname-postgres-data:/var/lib/postgresql/data
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-redis:
        container_name: $$cap_appname-redis
        image: redis:6-alpine
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-clickhouse:
        # KEEP CLICKHOUSE-SERVER VERSION IN SYNC WITH
        # https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/templates/clickhouse_instance.yaml#L88
        image: yandex/clickhouse-server:21.6.5
        depends_on:
            - $$cap_appname-kafka
            - $$cap_appname-zookeeper
        ports:
            - '8123:8123'
            - '9000:9000'
            - '9440:9440'
            - '9009:9009'
        volumes:
            - /root/apps/posthog/ee/idl:/idl
            - /root/apps/posthog/docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - /root/apps/posthog/docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
            - /root/apps/posthog/docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-zookeeper:
        image: wurstmeister/zookeeper
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-kafka:
        image: wurstmeister/kafka
        depends_on:
            - $$cap_appname-zookeeper
        ports:
            - '9092:9092'
        environment:
            KAFKA_ADVERTISED_HOST_NAME: srv-captain--$$cap_appname-kafka
            KAFKA_ZOOKEEPER_CONNECT: srv-captain--$$cap_appname-zookeeper:2181
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        container_name: $$cap_appname-web
        depends_on:
            - $$cap_appname-db
            - $$cap_appname-redis
            - $$cap_appname-clickhouse
            - $$cap_appname-kafka
        environment:
            DATABASE_URL: postgres://posthog:posthog@srv-captain--$$cap_appname-db:5432/posthog
            REDIS_URL: redis://srv-captain--$$cap_appname-redis:6379/
            KAFKA_URL: 'kafka://srv-captain--$$cap_appname-kafka'
            CLICKHOUSE_HOST: 'srv-captain--$$cap_appname-clickhouse'
            CLICKHOUSE_DATABASE: 'posthog'
            CLICKHOUSE_SECURE: 'false'
            CLICKHOUSE_VERIFY: 'false'
            SECRET_KEY: $$cap_posthog_secret_key
            PGHOST: srv-captain--$$cap_appname-db
            PGUSER: posthog
            PGPASSWORD: posthog
        image: posthog/posthog:latest
        #links:
        #    - db:db
        #    - redis:redis
        #    - clickhouse:clickhouse
        #    - kafka:kafka
        ports:
            - 8001:8000
        caproverExtra:
            containerHttpPort: '8001'
#volumes:
#    $$cap_appname-postgres-data:
#version: '3'
